# Generated by Django 3.0.8 on 2020-08-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='text',
            field=models.TextField(),
        ),
    ]
